FROM ubuntu
RUN apt-get update
RUN apt-get install -yq git build-essential make libsqlite3-dev sqlite3
WORKDIR /root
RUN git clone https://github.com/aiqbal84/facebooc.git
RUN cd facebooc
WORKDIR /root/facebooc
RUN make all
EXPOSE 16000
CMD ["bash"]
